const newmenus = [{
  "authority": null,
  "children": [
    // {
    //   "authority": null,
    //   "children": [],
    //   "code": null,
    //   "component": "views/formAuth/resource/index",
    //   "icon": "icon-yonghuguanli",
    //   "id": 1501,
    //   "keepAlive": "0",
    //   "label": "资源权限",
    //   "name": "资源权限",
    //   "parentId": 1500,
    //   "path": "/formAuth/resource",
    //   "redirect": null,
    //   "sort": 1,
    //   "spread": false,
    //   "type": "0"
    // },
    // {
    //   "authority": null,
    //   "children": [],
    //   "code": null,
    //   "component": "views/formAuth/menu/index",
    //   "icon": "icon-yonghuguanli",
    //   "id": 1502,
    //   "keepAlive": "0",
    //   "label": "菜单权限",
    //   "name": "菜单权限",
    //   "parentId": 1500,
    //   "path": "/formAuth/menu",
    //   "redirect": null,
    //   "sort": 1,
    //   "spread": false,
    //   "type": "0"
    // }
  ],
  "code": null,
  "component": "views/safeAudit/index",
  "icon": "icon-quanxianguanli",
  "id": 1600,
  "keepAlive": "0",
  "label": "安全审计",
  "meta": {},
  "name": "安全审计",
  "parentId": 1000,
  "path": "/upms/safeAudit",
  "redirect": null,
  "sort": 0,
  "spread": false,
  "type": "0",
},
  // {
  //   "authority": null,
  //   "children": [
  //     {
  //       "authority": null,
  //       "children": [],
  //       "code": null,
  //       "component": "views/ram/hdata/hive/index",
  //       "icon": "icon-yonghuguanli",
  //       "id": 10100,
  //       "keepAlive": "0",
  //       "label": "hive",
  //       "name": "hive",
  //       "parentId": 10000,
  //       "path": "/ram/hdata/hive",
  //       "redirect": null,
  //       "sort": 1,
  //       "spread": false,
  //       "type": "0"
  //     },
  //     {
  //       "authority": null,
  //       "children": [],
  //       "code": null,
  //       "component": "views/ram/hdata/impala/index",
  //       "icon": "icon-yonghuguanli",
  //       "id": 10200,
  //       "keepAlive": "0",
  //       "label": "impala",
  //       "name": "impala",
  //       "parentId": 10000,
  //       "path": "/ram/hdata/impala",
  //       "redirect": null,
  //       "sort": 1,
  //       "spread": false,
  //       "type": "0"
  //     }
  //   ],
  //   "code": null,
  //   "component": "Layout",
  //   "icon": "icon-quanxianguanli",
  //   "id": 10000,
  //   "keepAlive": "0",
  //   "label": "HData",
  //   "meta": {},
  //   "name": "HData",
  //   "parentId": -1,
  //   "path": "/hdata",
  //   "redirect": null,
  //   "sort": 0,
  //   "spread": false,
  //   "type": "0",
  // }
];

export default newmenus;
