const newmenus = [{
  "authority": null,
  "children": [
    {
      "authority": null,
      "children": [],
      "code": null,
      "component": "views/ram/resourceManage/index",
      "icon": "icon-yonghuguanli",
      "id": 9100,
      "keepAlive": "0",
      "label": "资源管理",
      "name": "资源管理",
      "parentId": 9000,
      "path": "/ram/resourceManage",
      "redirect": null,
      "sort": 1,
      "spread": false,
      "type": "0"
    }
  ],
  "code": null,
  "component": "Layout",
  "icon": "icon-quanxianguanli",
  "id": 9000,
  "keepAlive": "0",
  "label": "资源管理",
  "meta": {},
  "name": "资源管理",
  "parentId": -1,
  "path": "/ram",
  "redirect": null,
  "sort": 0,
  "spread": false,
  "type": "0",
},
{
  "authority": null,
  "children": [
    {
      "authority": null,
      "children": [],
      "code": null,
      "component": "views/ram/hdata/hive",
      "icon": "icon-yonghuguanli",
      "id": 10100,
      "keepAlive": "0",
      "label": "hive",
      "name": "hive",
      "parentId": 10000,
      "path": "/ram/Hive",
      "redirect": null,
      "sort": 1,
      "spread": false,
      "type": "0"
    }
  ],
  "code": null,
  "component": "Layout",
  "icon": "icon-quanxianguanli",
  "id": 10000,
  "keepAlive": "0",
  "label": "HData",
  "meta": {},
  "name": "HData",
  "parentId": -1,
  "path": "/hdata",
  "redirect": null,
  "sort": 0,
  "spread": false,
  "type": "0",
}];

export default newmenus;
